enter: 76
return: 36
fn: 63
control: 59
left_control: 59
option: 58
left_option: 58
command: 55
left_command: 55
shift: 56
left_shift: 56
right_shift: 60
right_control: 62
right_command: 55
right_option: 61
left: 123
right: 124
down: 125
up: 126
home: 115
end: 119
page_up: 116
page_down: 121
esc: 53
caps_lock: 57
space: 49
tab: 48
delete: 51
"1": 18
"2": 19
"3": 20
"4": 21
"5": 23
"6": 22
"7": 26
"8": 28
"9": 25
"0": 29
"`": 50
"[": 33
"]": 30
"\\": 42
";": 41
"'": 39
"-": 27
"=": 24
q: 12
w: 13
e: 14
r: 15
t: 17
y: 16
u: 32
i: 34
o: 31
p: 35
a: 0
s: 1
d: 2
f: 3
g: 5
h: 4
j: 38
k: 40
l: 37
z: 6
x: 7
c: 8
v: 9
b: 11
n: 45
m: 46
",": 43
".": 47
"/": 44

